mooc/urls.py
from django.conf.urls import include, url
from views import *
urlpatterns = [
    url(r'^$', mooc_list, name='mooc_list'),
    url(r'^(?P<id>\d+)/$', mooc_detail, name='mooc_detail'),
    url(r'^(?P<id>\d+)/add$', course_add, name='course_add'),
    url(r'^(?P<id>\d+)/delete$', course_delete, name='course_delete'),
    url(r'^(?P<id>\d+)/back$', back, name='back'),
    url(r'^(?P<id>\d+)/detect$', course_detect, name='course_detect'),
    url(r'^(?P<id>\d+)/mates$', show_who_choose_this_class, name='show_who_choose_this_class'),
]

mysite3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import index, register
from django.contrib.auth.views import login, logout_then_login
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/$', index, name='index'),
    url(r'^accounts/register/$', register, name='register'),
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),
    url(r'^$', index, name='index'),
    url(r'^mooc/', include('mooc.urls')),
    url(r'^index/show', 'mooc.views.show_my_course', name='show_my_course'),

]

mooc/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

# Create your models here.


class Course(models.Model):
    course_name = models.CharField(max_length=50, verbose_name="课程名称及任课老师")
    course_time = models.CharField(max_length=50, verbose_name="开课时间")
    course_index = models.CharField(max_length=50, verbose_name="上课时间")
    SUBJECT_CHOICES = (
        ('IT', '信息科学与技术学院'),
        ('EE', '电气工程学院'),
        ('CE', '土木工程学院'),
        ('MA', '数学学院'),
        ('ME', '机械工程学院'),
        ('PH', '物理学院'),
        ('HS', '人文学院'),
    )
    course_subject = models.CharField(max_length=2, choices=SUBJECT_CHOICES, verbose_name="开课学院")
    course_description = models.TextField(max_length=200, verbose_name="课程简介")
    course_consume = models.IntegerField(verbose_name="周学时")
    course_choose = models.ManyToManyField(User, blank=True)

    def __unicode__(self):
        return self.course_name

    class Meta:
        ordering = ['id']
        verbose_name = "课程"
        verbose_name_plural = "西南交大选课系统"



class CourseAdmin(admin.ModelAdmin):
    list_display = ['course_name', 'course_subject']

mooc/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from mooc.models import Course
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
# Create your views here.

@login_required
def back(request, id):
    return HttpResponseRedirect('/index/')

@login_required
def mooc_list(request):
    ml = Course.objects.all()
    return render_to_response('mooc_list.html', {'ml': ml})


@login_required
def mooc_detail(request, id):
    try:
        md = Course.objects.get(id=str(id))
    except Course.DoesNotExist:
        raise Http404
    return render_to_response('mooc_detail.html', {'md': md})


@login_required
def course_add(request, id):
    try:
        user = User.objects.get(id=request.user.id)
        course = Course.objects.get(id=id)
        verify = User.objects.filter(course__id=id, id=request.user.id)
        if verify:
            messages.error(request, '已经选择该课程！')
        else:
            course.course_choose.add(user)
            course.save()
            messages.success(request, "选课成功！")
        return HttpResponseRedirect('/index/')
    except Course.DoesNotExist:
        raise Http404


@login_required
def course_delete(request, id):
    try:
        user = User.objects.get(id=request.user.id)
        course = Course.objects.get(id=id)
        verify = User.objects.filter(course__id=id, id=request.user.id)
        if not verify:
            messages.error(request, '尚未选择这门课程！')
        else:
            course.course_choose.remove(user)
            course.save()
            messages.success(request, "退课成功！")
        return HttpResponseRedirect('/index/')
    except Course.DoesNotExist:
        raise Http404


@login_required
def course_detect(request, id):
    try:
        md = Course.objects.get(id=str(id))
        user = User.objects.get(id=request.user.id)
        my_courses = user.course_set.all()
        course = Course.objects.get(id=id)
        a = set()
        for i in my_courses:
            if i.course_index[:5] == course.course_index[:5] and i.course_name != course.course_name:
                a.add(i)
            if i.course_index[6:11] == course.course_index[:5] and i.course_name != course.course_name:
                a.add(i)
            if i.course_index[:5] == course.course_index[6:11] and i.course_name != course.course_name:
                a.add(i)
            if i.course_index[6:11] == course.course_index[6:11] and i.course_name != course.course_name:
                a.add(i)
        if len(a):
            for j in a:
                messages.error(request, '检测到冲突! %s 与 %s 有冲突！ ' % (j.course_name.encode('utf-8'), course.course_name.encode('utf-8')))
            return HttpResponseRedirect('/index/')
        else:
            messages.success(request, "无冲突！")
            return HttpResponseRedirect('/index/')
    except Course.DoesNotExist:
        raise Http404

@login_required
def show_my_course(request):
    user = User.objects.get(id=request.user.id)
    my_course = user.course_set.all()
    return render_to_response('mooc_select_show.html', {'my_course': my_course})


@login_required
def show_who_choose_this_class(request, id):
    course = Course.objects.get(id=id)
    class_mates = course.course_choose.all()
    return render_to_response('mooc_class_mates.html', {'class_mates': class_mates})

mysite3/views.py
#-*- coding:utf-8 -*-
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib import auth
from django.template import RequestContext
# from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
# Create your views here.


def index(request):
    return render_to_response('index.html', locals(), context_instance=RequestContext(request))

class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"),
        strip=False,
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."))

    class Meta:
        model = User
        fields = ("username",)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect('/accounts/login/', content_type=RequestContext(request))
    else:
        form = UserCreationForm()
    return render_to_response('register.html', locals(), context_instance=RequestContext(request))

templates/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<style type="text/css">
  body{color:#efd;background:#453;padding:0 5em;margin:0}
  h1{padding:2em 1em;background:#675}
  h2{color:#bf8;border-top:1px dotted #fff;margin-top:2em}
  a{color:#bf8;padding:1em 1em;background:#675}
  p{margin:1em 0}
</style>
<body>
{% if not request.user.is_authenticated %}
<a href="{% url 'register' %}">注册</a>
{% endif %}
{% if request.user.is_authenticated %}
    <p>{{ request.user }}您已经登录</p>
    <h1>欢迎使用西南交大选课系统！</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}注意: {% endif %}
            {{ message }}
        </li>
            {% endfor %}
    </ul>
    {% endif %}
    <a href="{% url 'mooc_list'%}">查看开课列表</a>
    <a href="{% url 'show_my_course' %}">查看我的课程</a>

    <a href="{% url 'logout' %}">登出</a>
{% else %}
    <p>您还没有登录<a href="{% url 'login' %}">登录</a></p>
{% endif %}
</body>
</html>

templates/login.html
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>选课系统登陆</title>
</head>
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">



<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
    <label>&nbsp;</label><input type="button" value="{% trans '注册' %}" onclick="window.open('http://127.0.0.1:8000/accounts/register','_blank');"/>
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

templates/mooc_class_mates.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<style type="text/css">
  body{color:#efd;background:#453;padding:0 5em;margin:0}
  h1{color:#bf8;padding:0.01em;background:#675}
  h2{color:#bf8;border-top:1px;margin-top:2em}
  a{color:#bf8;border-top:1px;margin-top:2em;background:#675}
  p{margin:1em 0}
</style>
<body>
{% for cm in class_mates %}
    <h1>{{ cm }}</h1>
{% endfor %}
<a href="{% url 'back' id=1 %}">返回主菜单</a>
</body>
</html>

templates/mooc_detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<style type="text/css">
  body{color:#efd;background:#453;padding:0 5em;margin:0}
  p{padding:1em 1em;background:#675}
  a{color:#bf8;border-top:1px;margin-top:2em;background:#675}
  h2{color:#bf8;border-top:1px dotted #fff;margin-top:2em}
</style>
<body>
<p>
课程号：
{{ md.id }}
</p>
<p>
课程名称：
{{ md.course_name }}
</p>
<p>
开课时间：
{{ md.course_time }}
</p>
<p>
开课学院：
{{ md.get_course_subject_display }}
</p>
<p>
周学时：
{{ md.course_consume }}
</p>
<p>
上课时间：
{{ md.course_index }}
</p>
<p>
课程简介:
{{ md.course_description }}
</p>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
        {% endfor %}
</ul>
{% endif %}
<br>
<a href="{% url 'course_add' id=md.id %}">添加课程</a>
<br>
<a href="{% url 'course_delete' id=md.id %}">退选课程</a>
<br>
<a href="{% url 'course_detect' id=md.id %}">冲突检测</a>
<br>
<a href="{% url 'show_who_choose_this_class' id=md.id %}">查看已选同学</a>
<br><br><br><br>
<a href="{% url 'back' id=1 %}">返回主菜单</a>
</body>
</html>

templates/mooc_list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<style type="text/css">
  body{color:#efd;background:#453;padding:0 5em;margin:0}
  th{padding:1em 11em;background:#675}
  tr{color:#bf8;border-top:1px dotted #fff;margin-top:1em}
  a{color:#bf8;border-top:1px;margin-top:2em;background:#675}
  h1{margin:2em 14em}
</style>
<body>
    <h1>点击课程名称查看详情</h1>
    <a href="{% url 'back' id=1 %}">返回主菜单</a>
    <br><br><br><br>
<table>
  <tr>
    <th>开课号</th>
    <th>课程名称</th>
    <th>开课科目</th>
  </tr>
{% for classes in ml %}
  <tr>
    <td>{{ classes.id }}</td>
    <td><a href="{% url 'mooc_detail' id=classes.id %}">{{ classes.course_name }}</a></td>
    <td>{{ classes.get_course_subject_display }}</td>
  </tr>
{% endfor %}
</table>
</body>
</html>

templates/mooc_select_show.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<style type="text/css">
  body{color:#efd;background:#453;padding:0 5em;margin:0}
  h1{padding:2em 1em;background:#675}
  h2{color:#bf8;padding:0.01em;background:#675}
  p{margin:1em 0}
  a{color:#bf8;border-top:1px;margin-top:2em;background:#675}
</style>
<body>
{#{{ my_course }}#}
{% for mc in my_course %}
    <h2>{{ mc }} {{ mc.course_index }}</h2>
{% endfor %}
<a href="{% url 'back' id=1 %}">返回主菜单</a>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>选课系统注册</title>
</head>
  <style type="text/css">
    body{color:#efd;background:#453;padding:0 5em;margin:0}
    h1{padding:2em 1em;background:#675}
    h2{color:#bf8;border-top:1px dotted #fff;margin-top:2em}
    p{margin:1em 0}
  </style>
<body>
<h1>注册选课系统账号</h1>
<p>请牢记账号密码，遗失请联系管理员</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="提交">
</form>
</body>
</html>